### ISSUE TITLE
Add pretty print button

### ISSUE THREAD

**Issue by bmwalters** [bmwalters/facepunch-glua-codemirror#10]
Perhaps we could get @FPtje's help in using [glualint-web](https://github.com/FPtje/glualint-web/)
Falco did it on [his glualint-web site](https://fptje.github.io/glualint-web/)

**Comment by FPtje** [comment]
What you would need for both linting and pretty printing is an API into the Haskell code that does all this stuff. Note that the javascript code for these two things would get pretty big.

**Comment by bmwalters** [comment]
My plan:
1. Follow [these steps](http://stackoverflow.com/a/31611311) to expose the Haskell to JS
2. Stick the compiled output + the call to the Haskell's main() in a single file, while following [these steps](https://developers.google.com/closure/compiler/docs/api-tutorial3#export) to keep the exposed functions around when I:
3. Shove it into Closure Compiler to hopefully drastically reduce the filesize
4. Use the optimized output in the extension

**Comment by bmwalters** [comment]
I finally got my Haskell -> JS compilation environment set up. It only took 4.75 hours.

For future me, here's the steps.
1. `sudo add-apt-repository ppa:hvr/ghc; sudo apt-get update`
1. `sudo apt-get install ghc-7.10.2`
1. `export PATH="/opt/ghc/7.10.2/bin:$PATH"`
1. `sudo apt-get install cabal-install`
1. `cabal update`
1. `cabal install http://ghcjs.luite.com/master.tar.gz`
1. `export PATH="$HOME/.cabal/bin:$PATH"`
1. `ghcjs-boot`
1. `git clone https://github.com/FPtje/GLuaFixer; cd GLuaFixer`
1. `cabal sandbox init`
1. `echo "compiler: ghcjs" >> cabal.config`
1. `cabal install --ghcjs --only-dependencies`
1. `sudo apt-get install uuagc`
1. `./AGGenerator.sh` (if this fails edit AGGenerator.sh and remove the `--optimize` flags)
1. `cabal build glualint`

Now I can finally start hacking on glualint-web.

(Edit) Here are the added steps for building glualint-lib:
1. `cd ..`
1. `git clone https://github.com/bmwalters/glualint-lib; cd glualint-lib`
1. `cabal sandbox init`
1. `mv ../GLuaFixer/gluafixer.cabal ../GLuaFixer/glualint-lib.cabal`
1. `cabal sandbox add-source ../GLuaFixer`
1. `cabal update`
1. `cabal install --only-dependencies`
1. `cabal build`

**Comment by bmwalters** [comment]
Progress!
![](https://i.imgur.com/rqARO0D.png)

**Comment by bmwalters** [comment]
Well, I've [got the lint function pretty much done](https://github.com/bmwalters/glualint-lib/blob/bf8acbd989249010d6ab1ece1af8582964657a27/src/Main.hs).
![](https://i.imgur.com/CC1eX6T.png)
(I'm not sure what took longer - learning enough Haskell to get that working or getting my compilation environment set up...)

I also ran the compiled output through the Closure Compiler (I had to use the application because the file was too large for the API):
`java -jar closure-compiler-v20170218.jar --js all.js --js_output_file compiled.js --compilat
ion_level ADVANCED`
[The file](https://github.com/bmwalters/glualint-lib/blob/9015ec8c5afdb56045960979ee082513681c6cfd/compiled.js) went from ~3.7MB to ~1.0MB which I would still say is too large but closer to acceptable (a typical Facepunch thread loads about 1.5MB of content, skyrocketing up if the thread contains embeds for twitter/youtube etc.)

I'm happy enough to work on adding the linting functionality to the extension tonight though 👍

**Comment by bmwalters** [comment]
!!!
![](https://i.imgur.com/SUy3JaM.png)
